---
- hosts: localhost
  tasks:
  - name: Create security group
    ec2_group:
        name: "pragathi_security_group"
        description: "security group for ssh and http"
        region: us-west-2 
        rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
        rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
    register: basic_firewall
  
  - name: provision ec2 instance
    ec2:
       key_name: Test-awskey
       region: us-west-2
       instance_type: t2.micro
       image: ami-a58d0dc5
       wait: yes
       wait_timeout: 500
       count: 1
       instance_tags:
           Name: awslabserver
           Owner: pragathi 
       group: pragathi_security_group
    register: ec2 
   
  - name: wait for ssh to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: "{{ec2.instances}}"

